config/routes.rb
Rails.application.routes.draw do
  resources :users_facilities
  resources :roles
  resources :facilities
  resources :users
  root 'users#index'
  get 'user/new2/:user_id', to:'users#new2', as: 'new2_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/facility.rb
class Facility < ApplicationRecord
	# has_many :user_facility
	# has_many :users, through: :user_facility
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def facility_params
      params.require(:facility).permit(:name)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_for(facility) do |f| %>
  <% if facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facilities.each do |facility| %>
      <tr>
        <td><%= facility.name %></td>
        <td><%= link_to 'Show', facility %></td>
        <td><%= link_to 'Edit', edit_facility_path(facility) %></td>
        <td><%= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facility', new_facility_path %>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form', facility: @facility %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @facility.name %>
</p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>