config/routes.rb
Rails.application.routes.draw do
  resources :users_facilities
  resources :roles
  resources :facilities
  resources :users
  root 'users#index'
  get 'user/new2/:user_id', to:'users#new2', as: 'new2_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/users_facility.rb
class UsersFacility < ApplicationRecord
	belongs_to :user
	# belongs_to :fecility
end

app/controllers/users_facilities_controller.rb
class UsersFacilitiesController < ApplicationController
  before_action :set_users_facility, only: [:show, :edit, :update, :destroy]

  # GET /users_facilities
  # GET /users_facilities.json
  def index
    @users_facilities = UsersFacility.all
  end

  # GET /users_facilities/1
  # GET /users_facilities/1.json
  def show
  end

  # GET /users_facilities/new
  def new
    @users_facility = UsersFacility.new
  end

  # GET /users_facilities/1/edit
  def edit
  end

  # POST /users_facilities
  # POST /users_facilities.json
  def create
    @users_facility = UsersFacility.new(users_facility_params)

    respond_to do |format|
      if @users_facility.save
        format.html { redirect_to @users_facility, notice: 'Users facility was successfully created.' }
        format.json { render :show, status: :created, location: @users_facility }
      else
        format.html { render :new }
        format.json { render json: @users_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_facilities/1
  # PATCH/PUT /users_facilities/1.json
  def update
    respond_to do |format|
      if @users_facility.update(users_facility_params)
        format.html { redirect_to @users_facility, notice: 'Users facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @users_facility }
      else
        format.html { render :edit }
        format.json { render json: @users_facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_facilities/1
  # DELETE /users_facilities/1.json
  def destroy
    @users_facility.destroy
    respond_to do |format|
      format.html { redirect_to users_facilities_url, notice: 'Users facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_facility
      @users_facility = UsersFacility.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def users_facility_params
      params.require(:users_facility).permit(:user_id, :facility_id)
    end
end

app/helpers/users_facilities_helper.rb
module UsersFacilitiesHelper
end

app/views/users_facilities/_form.html.erb
<%= form_for(users_facility) do |f| %>
  <% if users_facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users_facility.errors.count, "error") %> prohibited this users_facility from being saved:</h2>

      <ul>
      <% users_facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :facility_id %>
    <%= f.text_field :facility_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_facilities/edit.html.erb
<h1>Editing Users Facility</h1>

<%= render 'form', users_facility: @users_facility %>

<%= link_to 'Show', @users_facility %> |
<%= link_to 'Back', users_facilities_path %>

app/views/users_facilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users Facilities</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Facility</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_facilities.each do |users_facility| %>
      <tr>
        <td><%= users_facility.user_id %></td>
        <td><%= users_facility.facility_id %></td>
        <td><%= link_to 'Show', users_facility %></td>
        <td><%= link_to 'Edit', edit_users_facility_path(users_facility) %></td>
        <td><%= link_to 'Destroy', users_facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users Facility', new_users_facility_path %>

app/views/users_facilities/new.html.erb
<h1>New Users Facility</h1>

<%= render 'form', users_facility: @users_facility %>

<%= link_to 'Back', users_facilities_path %>

app/views/users_facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @users_facility.user_id %>
</p>

<p>
  <strong>Facility:</strong>
  <%= @users_facility.facility_id %>
</p>

<%= link_to 'Edit', edit_users_facility_path(@users_facility) %> |
<%= link_to 'Back', users_facilities_path %>